# Jekyll configuration for www.webtrees.net

title: webtrees
email: fisharebest@gmail.com
description: >
  webtrees is a web application that allows you to publish your genealogy online,
  collaborate with family members and take control of your data.
latest_version: "2.0.1"
latest_version_17: "1.7.16"
url: "https://webtrees.github.io"
this_github_repo: webtrees/webtrees.github.io
edit_text: Edit this page
baseurl: ""
date_format: "%b %-d, %Y"
show_excerpts: true
permalink: pretty
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title:output_ext
  readme:
    output: true
paginate: 5
paginate_path: "/blog/page:num/"

# External accounts
main_github_repo:  fisharebest/webtrees

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
